PROGRAM my_test

! Code converted using TO_F90 by Alan Miller
! Date: 2002-02-08  Time: 17:53:39

!***DATE WRITTEN   830501   (YYMMDD)
!***REVISION DATE  890801, 930101   (YYMMDD)

!     CQCBJ IS A QUICK CHECK ROUTINE FOR THE COMPLEX J BESSEL FUNCTION
!     GENERATED BY SUBROUTINE CBESJ.

!     CQCBJ GENERATES SEQUENCES OF J AND H BESSEL FUNCTIONS FROM CBESJ
!     AND CBESH AND CHECKS THE WRONSKIANS

!     J(FNU,Z)*H(FNU+1,1,Z)-J(FNU+1,Z)*H(FNU,1,Z)=2/(PI*I*Z)   Y.GE.0

!     J(FNU,Z)*H(FNU+1,2,Z)-J(FNU+1,Z)*H(FNU,2,Z)=-2/(PI*I*Z)  Y.LT.0

!     IN THEIR RESPECTIVE HALF PLANES.

!     THE PARAMETER MQC CAN HAVE VALUES 1 (THE DEFAULT) FOR A FASTER,
!     LESS DEFINITIVE TEST OR 2 FOR A SLOWER, MORE DEFINITIVE TEST.

!     MACHINE CONSTANTS ARE DEFINED IN FUNCTIONS I1MACH, R1MACH, AND
!     D1MACH. THESE MUST BE SELECTED BY THE USER OR SET ACCORDING TO
!     PROLOGUE INSTRUCTIONS.

USE Complex_Bessel
IMPLICIT NONE

INTEGER       :: kode, np, nzj, ierrj, i
INTEGER       :: n1 = 2
COMPLEX (dp)  :: z, cj(5), cj_1(4)
REAL (dp)     :: fnu, x

kode = 1
nzj = 1
x = 0.0

z = CMPLX(x, 0.0, KIND=dp)

fnu = n1-2
np = 5

IF (fnu >= 0) THEN
  CALL cbesj(z, fnu, kode, np, cj, nzj, ierrj)
ELSE
  fnu = 0
  np = 4
  CALL cbesj(z, fnu, kode, np, cj_1, nzj, ierrj)
  cj(1) = COMPLEX( -REAL(cj_1(2)), AIMAG(cj_1(2))  )
  DO i = 2, 5
    cj(i) = cj_1(i-1)
  END DO
END IF
!cj(1) = COMPLEX( -REAL(cj(2)), IMAG(cj(2)) )

print*, ierrj
print*, cj

END PROGRAM my_test
